/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PackagesSlugRouteImport } from './routes/packages.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesSlugRoute = PackagesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PackagesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/packages': typeof PackagesRouteWithChildren
  '/payment': typeof PaymentRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/packages/$slug': typeof PackagesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/packages': typeof PackagesRouteWithChildren
  '/payment': typeof PaymentRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/packages/$slug': typeof PackagesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/packages': typeof PackagesRouteWithChildren
  '/payment': typeof PaymentRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/packages/$slug': typeof PackagesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/gallery'
    | '/packages'
    | '/payment'
    | '/blog/$slug'
    | '/packages/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/gallery'
    | '/packages'
    | '/payment'
    | '/blog/$slug'
    | '/packages/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/gallery'
    | '/packages'
    | '/payment'
    | '/blog/$slug'
    | '/packages/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  PackagesRoute: typeof PackagesRouteWithChildren
  PaymentRoute: typeof PaymentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$slug': {
      id: '/packages/$slug'
      path: '/$slug'
      fullPath: '/packages/$slug'
      preLoaderRoute: typeof PackagesSlugRouteImport
      parentRoute: typeof PackagesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface PackagesRouteChildren {
  PackagesSlugRoute: typeof PackagesSlugRoute
}

const PackagesRouteChildren: PackagesRouteChildren = {
  PackagesSlugRoute: PackagesSlugRoute,
}

const PackagesRouteWithChildren = PackagesRoute._addFileChildren(
  PackagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  PackagesRoute: PackagesRouteWithChildren,
  PaymentRoute: PaymentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
